config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
]

home/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from . import views
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', LandingPage.as_view(), name='home'),
    path('add-donation/', AddDonation.as_view(), name='add-donation'),
    path('login/', views.login_view, name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', Profile.as_view(), name='profile'),
    path('user/edit/', AccessEditUser.as_view(), name='access-edit-user'),
    path('user/edit/details', EditUser.as_view(), name='edit-user'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('contact/', Contacts.as_view(), name='contact'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', views.activate_new_password, name='password_reset_confirm'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Institution(models.Model):
    institution_types = [(1, 'Fundacja'),
                         (2, 'Organizacja pozarządowa'),
                         (3, 'Zbiórka lokalna')]

    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    type = models.IntegerField(choices=institution_types, default=1)
    categories = models.ManyToManyField('Category')

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField('Category')
    institution = models.ForeignKey('Institution', on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=30)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_taken = models.BooleanField(default=False)

    def __str__(self):
        return f"quantity: {self.quantity}, adres: {self.address}, phone: {self.phone_number}, city: {self.city},  " \
               f"zip-code: {self.zip_code}, pick_up_date: {self.pick_up_date}, pick_up_time: {self.pick_up_time}"

home/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm, AuthenticationForm


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'placeholder': 'Imię'}), label='')
    last_name = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'placeholder': 'Nazwisko'}), label='')
    email = forms.EmailField(max_length=128, widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='')
    password1 = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}), label='')
    password2 = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Powtórz hasło'}),
                                label='')

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.EmailField(max_length=128, widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='')

    password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}), label='')


class UserEditAccessForm(forms.ModelForm):
    password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}), label='')

    class Meta:
        model = get_user_model()
        fields = ['password']


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'placeholder': 'Imię'}), label='')
    last_name = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'placeholder': 'Nazwisko'}), label='')
    email = forms.EmailField(max_length=128, widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='')

    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name']


class UserEditPasswordForm(forms.ModelForm):
    old_password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Stare hasło'}),
                                   label='')
    password1 = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Nowe hasło'}),
                                label='')
    password2 = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Powtórz nowe hasło'}),
                                label='')

    class Meta:
        model = get_user_model()
        fields = []


class NewPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']

home/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.contrib import messages
from django.views.generic import TemplateView

from home import forms
from home.models import *
from .forms import UserLoginForm
from .tokens import account_activation_token
from django.db.models.query_utils import Q


class LandingPage(View):

    def get(self, request):
        sum_of_bags = Donation.objects.aggregate(Sum('quantity'))
        sum_of_institutions = Institution.objects.count()
        fundations = Institution.objects.filter(type=1)
        organizations = Institution.objects.filter(type=2)
        local_charities = Institution.objects.filter(type=3)

        return render(request, 'home/index.html',
                      {'sum_of_bags': sum_of_bags, 'sum_of_institutions': sum_of_institutions,
                       'fundations': fundations, 'organizations': organizations, 'local_charities': local_charities})


class AddDonation(LoginRequiredMixin, View):
    login_url = 'home:login'
    template_name = 'home/form.html'
    model = Donation

    def get(self, request):
        categories = Category.objects.all()
        institutions = Institution.objects.all()
        return render(request, self.template_name, {'categories': categories, 'institutions': institutions})

    def post(self, request):
        quantity = request.POST.get('quantity')
        categories = request.POST.get('category')
        institution = request.POST.get('organization')
        address = request.POST.get('address')
        phone_number = request.POST.get('phone')
        city = request.POST.get('city')
        zip_code = request.POST.get('postcode')
        pick_up_date = request.POST.get('data')
        pick_up_time = request.POST.get('time')
        user = request.user

        donation = Donation(quantity=quantity, institution_id=institution, address=address,
                            phone_number=phone_number, city=city, zip_code=zip_code, pick_up_date=pick_up_date,
                            pick_up_time=pick_up_time, user=user)
        donation.save()
        donation.categories.add(categories)
        return redirect('home:home')


class Register(View):
    template_name = 'home/register.html'
    model = get_user_model()

    def get(self, request):
        form = forms.RegistrationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = forms.RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activate_email(request, user, form.cleaned_data.get('email'))
            return redirect('home:login')
        else:
            return render(request, self.template_name, {'form': form})


def activate_email(request, user, to_email):
    mail_subject = 'Activate your user account.'
    message = render_to_string('home/template_activate_account.html', {
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Drogi {user}, przejdź do swojej skrzynki pocztowej w celu aktywacji konta.')
    else:
        messages.error(request,
                       f'Pojawił się problem z wysłaniem maila na {to_email}, sprawdź czy nie popełniłeś literówki.')


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Dziękujemy za potwierdzenie emaila. Możesz się teraz zalogować.')
        return redirect('home:login')
    else:
        messages.error(request, 'Link do aktywacji nie działa!')

    return redirect('home:home')


def login_view(request):
    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"], )

            if user is not None:
                login(request, user)
                return redirect("home:home")

        else:
            return redirect('home:register')

    form = UserLoginForm()

    return render(
        request=request,
        template_name="home/login.html",
        context={"form": form}
    )


def logout_view(request):
    logout(request)
    return redirect('home:home')


class Profile(LoginRequiredMixin, View):
    template_name = 'home/user.html'

    def get(self, request):
        users = get_user_model()
        user = users.objects.get(pk=request.user.pk)
        donations = Donation.objects.filter(user=user.pk)

        return render(request, self.template_name, {'user': user, 'donations': donations})

    def post(self, request):
        users = get_user_model()
        user = users.objects.get(pk=request.user.pk)
        donations = Donation.objects.filter(user=user).order_by('pick_up_date')
        id_donation = request.POST.get('id_donation')
        donation = donations.get(pk=id_donation)

        if donation.is_taken:

            donation.is_taken = False
            donation.save()

        elif not donation.is_taken:

            donation.is_taken = True
            donation.save()

        return redirect('home:profile')


class AccessEditUser(LoginRequiredMixin, View):
    template_name = 'home/edit-user-access.html'

    def get(self, request):
        form = forms.UserEditAccessForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = forms.UserEditAccessForm(request.POST)
        if form.is_valid():
            password_entered = form.cleaned_data['password']
            user_password = request.user.password
            authenticate_user = check_password(password_entered, user_password)
            if authenticate_user:
                return redirect('home:edit-user')

            else:
                messages.error(request, "Podano nieprawidłowe hasło.")
                return redirect('home:access-edit-user')


class EditUser(LoginRequiredMixin, View):
    template_name = 'home/edit-user.html'

    def get(self, request):
        form = forms.UserEditForm()
        form_password = forms.UserEditPasswordForm()

        return render(request, self.template_name, {'form': form, 'form_password': form_password})

    def post(self, request):
        users = get_user_model()
        user = users.objects.get(pk=request.user.pk)
        form = forms.UserEditForm(request.POST)
        form_password = forms.UserEditPasswordForm(request.POST)

        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            user.username = form.cleaned_data['email']
            user.save()
            messages.success(request, "Zmieniono dane.")
            return redirect('home:edit-user')

        if form_password.is_valid():
            old_password = form_password.cleaned_data['old_password']
            password1 = form_password.cleaned_data['password1']
            password2 = form_password.cleaned_data['password2']
            if user.check_password(old_password):
                if password1 == password2:
                    user.set_password(password1)
                    user.save()
                    update_session_auth_hash(request, user)
                    return redirect('home:profile')
                else:
                    messages.error(request, 'Podane hasła nie są takie same!')
                    return redirect('home:edit-user')
            else:
                messages.error(request, 'Stare hasło jest niepoprawne!')
                return redirect('home:edit-user')


class Contacts(View):
    def post(self, request):
        name = request.POST.get("name")
        surname = request.POST.get("surname")
        message = request.POST.get("message")
        admins = get_user_model().objects.filter(is_staff=True)
        if name and surname and message:
            mail_subject = 'Zapytanie od użytkownika strony'
            message = f'Imię: {name}, Nazwisko: {surname}. Zapytanie: {message}'
            admins_emails = []
            for admin in admins:
                admins_emails.append(admin.email)
            email = EmailMessage(mail_subject, message, to=admins_emails)
            email.send()
            return redirect('home:home')

        return redirect('home:home')


class PasswordResetView(View):
    template_name = 'home/password_reset_form.html'

    def get(self, request):
        form = PasswordResetForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = PasswordResetForm(request.POST)
        User = get_user_model()
        if form.is_valid():

home/templates/home/edit-user-access.html
{% extends 'base.html' %}
{% block container %}
    <header>
        {% include 'partials/_menu.html' %}
    </header>

    <section class="login-page">
        <h2>Podaj hasło, aby edytować swoje konto.</h2>
        <form action="" method="post">{% csrf_token %}

            <div class="form-group">
                {{ form }}
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                    <p>{{ message }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
            </div>

            <div class="form-group form-group--buttons">
                <button class="btn" type="submit">Potwierdź</button>
            </div>
        </form>
    </section>
{% endblock %}

home/templates/home/edit-user.html
{% extends 'base.html' %}
{% block container %}
    <header>
        {% include 'partials/_menu.html' %}
    </header>

    <section class="login-page">
        <h2>Edycja konta:</h2>
        <form method="post">{% csrf_token %}

            <div class="form-group">
            {% for fields in form %}
                <ul>{{ fields }}</ul>
            {% endfor %}
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <p>{{ message }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}


            <div class="form-group form-group--buttons">
                <button class="btn" type="submit">Potwierdź</button>
            </div>
            </div>
        </form>
        <form method="post">{% csrf_token %}

            <div class="form-group">
            {% for fields in form_password %}
                <ul>{{ fields }}</ul>
            {% endfor %}
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <p>{{ message }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}


            <div class="form-group form-group--buttons">
                <button class="btn" type="submit">Zmień hasło</button>
            </div>
            </div>
        </form>
    </section>
{% endblock %}

home/templates/home/form-confirmation.html
{% extends 'base.html' %}

{% block container %}
<header class="header--form-page">
        {% include 'partials/_menu.html' %}
      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% block container %}
    <header class="header--main-page">
        {% include 'partials/_menu.html' %}

        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1>
                    Zacznij pomagać!<br/>
                    Oddaj niechciane rzeczy w zaufane ręce
                </h1>
            </div>
        </div>
    </header>

    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                {% for key, value in sum_of_bags.items %}
                    <em>{{ value }}</em>
                {% endfor %}
                <h3>Oddanych worków</h3>
            </div>

            <div class="stats--item">
                <em>{{ sum_of_institutions }}</em>
                <h3>Wspartych organizacji</h3>
            </div>
        </div>
    </section>

    <section id="steps" class="steps">
        <h2>Wystarczą 4 proste kroki</h2>

        <div class="steps--container">
            <div class="steps--item">
                <span class="icon icon--hands"></span>
                <h3>Wybierz rzeczy</h3>
                <p>ubrania, zabawki, sprzęt i inne</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--arrow"></span>
                <h3>Spakuj je</h3>
                <p>skorzystaj z worków na śmieci</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--glasses"></span>
                <h3>Zdecyduj komu chcesz pomóc</h3>
                <p>wybierz zaufane miejsce</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--courier"></span>
                <h3>Zamów kuriera</h3>
                <p>kurier przyjedzie w dogodnym terminie</p>
            </div>
        </div>

        <a href="{% url 'home:register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
        <div class="about-us--text">
            <h2>O nas</h2>
            <p>Zbieramy listę sprawdzonych instytucji, by pomóc w ich dotacji.</p>
            <img src="/static/images/signature.svg" class="about-us--text-signature" alt="Signature"/>
        </div>
        <div class="about-us--image"><img src="/static/images/about-us.jpg" alt="People in circle"/></div>
    </section>

    <section id="help" class="help">
        <h2>Komu pomagamy?</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="#1" class="btn btn--without-border active">Fundacjom</a></li>
            <li data-id="2"><a href="#2" class="btn btn--without-border active">Organizacjom pozarządowym</a></li>
            <li data-id="3"><a href="#3" class="btn btn--without-border active">Lokalnym zbiórkom</a></li>
        </ul>

        <!-- SLIDE 1 -->
        <div class="help--slides active" data-id="1">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.</p>


            <ul class="help--slides-items">{% for fundation in fundations %}
                <li>
                    <div class="col">
                        <div class="title">{{ fundation.name }}</div>
                        <div class="subtitle">{{ fundation.description }}</div>
                    </div>

                    <div class="col">{% for categories in fundation.categories.all %}
                        <div class="text">{{ categories.name }}</div>{% endfor %}
                    </div>
                </li>{% endfor %}
            </ul>

        </div>


        <!-- SLIDE 2 -->
        <div class="help--slides" data-id="2">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Organizacji, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.
            </p>
            <ul class="help--slides-items">{% for organization in organizations %}
                <li>
                    <div class="col">
                        <div class="title">{{ organization.name }}</div>
                        <div class="subtitle">{{ organization.description }}</div>
                    </div>

                    <div class="col">{% for categories in organization.categories.all %}
                        <div class="text">{{ categories.name }}</div>{% endfor %}
                    </div>
                </li>{% endfor %}
            </ul>
        </div>

        <!-- SLIDE 3 -->
        <div class="help--slides" data-id="3">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Instytucji, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.</p>
            <ul class="help--slides-items">{% for local_charity in local_charities %}
                <li>
                    <div class="col">
                        <div class="title">{{ local_charity.name }}</div>
                        <div class="subtitle">{{ local_charity.description }}</div>
                    </div>
                    <div class="col">{% for categories in local_charity.categories.all %}
                        <div class="text">{{ categories.name }}</div>{% endfor %}
                    </div>
                </li>{% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

home/templates/home/login.html
{% extends 'base.html' %}
{% block container %}
    <header>
        {% include 'partials/_menu.html' %}
    </header>

    <section class="login-page">
        <h2>Zaloguj się</h2>
        <form action="" method="post">{% csrf_token %}

            <div class="form-group">
                {% for fields in form %}
                    <ul>{{ fields }}</ul>
                {% endfor %}
            </div>
                        <div class="form-group">

                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'success' %}
                                    <div class="alert alert-success alert-dismissible" role="alert">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                        {{ message }}
                                    </div>
                                {% endif %}

                                {% if message.tags == 'error' %}
                                    <div class="alert alert-success alert-dismissible" role="alert">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                        {{ message }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}

            <div class="form-group form-group--buttons">
                <a href="{% url 'home:register' %}" class="btn btn--without-border">Załóż konto</a>
                <a href="{% url 'home:password_reset' %}" class="btn btn--without-border">Nie pamiętam hasła.</a>
                <button class="btn" type="submit">Zaloguj się</button>
            </div>
        </form>
    </section>
{% endblock %}

home/templates/home/password_reset_confirm.html
{% extends 'base.html' %}
{% block container %}
    <header>
        {% include 'partials/_menu.html' %}
    </header>
    <section class="help">
        <div class="container">
            <h1>Wpisz swoje nowe hasło.</h1>
        </div>
        <form method="POST">{% csrf_token %}
            <div class="form-group">
                {% for fields in form %}
                    <ul>{{ fields }}</ul>
                {% endfor %}
{#                {% if messages %}#}
{#                    {% for message in messages %}#}
{#                        {% if messeges.tag == 'error' %}#}
{#                            <p>{{ message }}</p>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}
{#                {% endif %}#}
                <div class="form-group form-group--buttons">
                    <button class="btn" type="submit">Utwórz nowe hasło</button>
                </div>
            </div>
        </form>
    </section>
{% endblock %}

home/templates/home/password_reset_done.html
{% extends 'base.html' %}
{% block container %}
    <header>
        {% include 'partials/_menu.html' %}
    </header>
    <section class="help">
        <div class="container">
            <h1>Na podany adres email wysłano link do zresetowania hasła.</h1>
        </div>
    </section>
{% endblock %}

home/templates/home/password_reset_form.html
{% extends 'base.html' %}
{% block container %}
    <header>
        {% include 'partials/_menu.html' %}
    </header>
    <section class="help">
        <div class="container">
            <h1>Zapomniałeś hasła?</h1>
            <p>Wpisz swój adres email w celu otrzymania linku z dalszymi instrukcjami.</p>
        </div>
        <form method="POST">{% csrf_token %}
            <div class="form-group">
                <p>{{ form }}</p>
                {% if messages %}
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div>
                <button class="btn" type="submit">Wyślij maila z instrukcjami</button>
            </div>
        </form>
    </section>
{% endblock %}

home/templates/home/register.html
{% extends 'base.html' %}
{% block container %}
    <header>
        {% include 'partials/_menu.html' %}
    </header>

    <section class="login-page">
        <h2>Załóż konto</h2>
        <form action="" method="post">{% csrf_token %}

            <div class="form-group">
                {% for fields in form %}
                    <ul>{{ fields }}</ul>
                {% endfor %}
            </div>
            {% if messages %}
                {% for message in messages %}

                        <div class="alert alert-success alert-dismissible" role="alert">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ message }}
                        </div>

                {% endfor %}
            {% endif %}
            <div class="form-group form-group--buttons">
                <a href="{% url 'home:login' %}" class="btn btn--without-border">Zaloguj się</a>
                <button class="btn" type="submit">Załóż konto</button>
            </div>
        </form>
    </section>
{% endblock %}

home/templates/home/template_activate_account.html
{% autoescape off %}
Cześć,

Kliknij w poniższy link aby dokończyć rejestrację:

http://{{ domain }}{% url 'home:activate' uidb64=uid token=token %}
{% endautoescape %}

home/templates/home/template_reset_password.html
{% autoescape off %}
Cześć,

Kliknij w poniższy link aby resetować hasło:


{{ protocol }}://{{ domain }}{% url 'home:password_reset_confirm' uidb64=uid token=token %}

{% endautoescape %}