config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
]

home/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from . import views
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', LandingPage.as_view(), name='home'),
    path('add-donation/', AddDonation.as_view(), name='add-donation'),
    path('login/', views.login_view, name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', Profile.as_view(), name='profile'),
    path('user/edit/', AccessEditUser.as_view(), name='access-edit-user'),
    path('user/edit/details', EditUser.as_view(), name='edit-user'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('contact/', Contacts.as_view(), name='contact'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', views.activate_new_password, name='password_reset_confirm'),
]

templates/partials/_footer.html
<footer>
    <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact" method="post" action="{% url 'home:contact' %}">{% csrf_token %}

            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię"/></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko"/></div>
            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

            <button class="btn" type="submit">Wyślij</button>

        </form>

    </div>
    <div class="bottom-line">
        <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="/static/images/icon-facebook.svg"/></a>
            <a href="#" class="btn btn--small"><img src="/static/images/icon-instagram.svg"/></a>
        </div>
    </div>
</footer>

templates/partials/_menu.html
<nav class="container container--70">
    <ul class="nav--actions">
        <li><a href="{% url 'home:login' %}">Zaloguj</a></li>
        <li class="highlighted"><a href="{% url 'home:register' %}">Załóż konto</a></li>
    </ul>
    <ul class="nav--actions">{% if user.is_authenticated %}
        <li class="logged-user">
            Witaj {{ user }}
            <ul class="dropdown">
                <li><a href="{% url 'home:profile' %}">Profil</a></li>
                <li><a href="{% url 'home:access-edit-user' %}">Ustawienia</a></li>
                {% if user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">Panel administracyjny</a></li>{% endif %}
                <li><a href="{% url 'home:logout' %}">Wyloguj</a></li>{% endif %}
            </ul>
        </li>
    </ul>
        <ul>{% if request.get_full_path == 'home:home' %}
            <li><a href='{% url 'home:home' %}' class="btn btn--without-border active">Start</a></li>
            <li><a href="#steps" class="btn btn--without-border">O co chodzi?</a></li>
            <li><a href="#about-us" class="btn btn--without-border">O nas</a></li>
            <li><a href="#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            <li><a href="{% url 'home:add-donation' %}#add_donation" class="btn btn--without-border">Przekaż dary</a></li>
            <li><a href="{% url 'home:contact' %}" class="btn btn--without-border">Kontakt</a></li>
        </ul>{% else %}
            <ul>
            <li><a href='{% url 'home:home' %}' class="btn btn--without-border active">Start</a></li>
            <li><a href='{% url 'home:home' %}#steps' class="btn btn--without-border">O co chodzi?</a></li>
            <li><a href="{% url 'home:home' %}#about-us" class="btn btn--without-border">O nas</a></li>
            <li><a href="{% url 'home:home' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            <li><a href="{% url 'home:add-donation' %}#add_donation" class="btn btn--without-border">Przekaż dary</a></li>
            <li><a href="{% url 'home:home' %}#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>{% endif %}
</nav>